App.Marriage/App.Marriage/Entities/QuestionBank.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionBank()
        {
            this.RequestQuestionSenario = new HashSet<RequestQuestionSenario>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Entity_Order { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestQuestionSenario> RequestQuestionSenario { get; set; }
    }
}

App.Marriage/App.Marriage/Entities/RegisterRequests.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterRequests()
        {
            this.RelationRequest = new HashSet<RelationRequest>();
            this.RequestQuestionSenario = new HashSet<RequestQuestionSenario>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> Person_Id { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<int> ResponseMessage { get; set; }
        public string Links { get; set; }
        public string RequestMessage { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelationRequest> RelationRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestQuestionSenario> RequestQuestionSenario { get; set; }
    }
}

App.Marriage/App.Marriage/Models/QuestionBank.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Marriage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBank
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Entity_Order { get; set; }
    
        public virtual Category Category { get; set; }
    }
}

App.Marriage/App.Marriage/Controllers/QuestionBanks/QuestionBankController.cs
using App.Marriage.Models.QuestionMV;
using DevExpress.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App.Marriage.Controllers.QuestionBanks
{
    public class QuestionBankController : Controller
    {

        private string QuestionBankView = "~/Views/QuestionBank/_QuestionBankGVP.cshtml";
        // GET: QuestionBanks
        public ActionResult Index()
        {
            return View();
        }

        [ValidateInput(false)]
        public ActionResult QuestionBankGVP()
        {
            var model = QuestionBankViewModel.GetQuestionBankList();
            return PartialView(QuestionBankView, model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult QuestionBankGVPAddNew([ModelBinder(typeof(DevExpressEditorsBinder))]  QuestionBankViewModel QuestionBank)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to insert the new QuestionBank in your model
                    QuestionBank.Create();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = QuestionBank.GetModelStateError(ModelState);
            var model = QuestionBankViewModel.GetQuestionBankList();
            return PartialView(QuestionBankView, model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult QuestionBankGVPUpdate([ModelBinder(typeof(DevExpressEditorsBinder))]  QuestionBankViewModel QuestionBank)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to update the QuestionBank in your model
                    QuestionBank.Update();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = QuestionBank.GetModelStateError(ModelState);
            var model = QuestionBankViewModel.GetQuestionBankList();
            return PartialView(QuestionBankView, model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult QuestionBankGVPDelete([ModelBinder(typeof(DevExpressEditorsBinder))] System.Int32 Id)
        {
            if (Id >= 0)
            {
                try
                {
                    // Insert here a code to delete the QuestionBank from your model
                    var QuestionBank = QuestionBankViewModel.Find(Id);
                    QuestionBank.Delete();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            var model = QuestionBankViewModel.GetQuestionBankList();
            return PartialView(QuestionBankView, model);
        }
    }
}

App.Marriage/App.Marriage/Controllers/RegisterRequestController.cs
using DevExpress.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.Marriage.Models.RegisterRequesMV;
using App.Marriage.Models.PersonMV;
using App.Marriage.DAL;
using App.Marriage.Helpars;
using App.Marriage.Models.RequestQuestionSenarioMV;
using App.Marriage.Models.QuestionMV;
using System.Threading.Tasks;

namespace App.Marriage.Controllers
{
    public class RegisterRequestController : Controller
    {
        // GET: RegisterRequest
        public ActionResult Index()
        {
            if (!UserHelpar.CanDo(Permissons.AcceptUser))
                return RedirectToAction("Unauthorized", "Home", null);
            return View();
        }
        #region RR
        [ValidateInput(false)]
        public ActionResult RegisterRequestGVP()
        {
            var model = RegisterRequestViewModels.Get_RegisterRequestsList();
            return PartialView("_RegisterRequestGVP", model);
        }
        public async Task<ActionResult> SendQuestions(int Id)
        {

            RegisterRequestsDAL rrDAL = new RegisterRequestsDAL(Id);
            rrDAL.RegisterRequests.RequestStatus = 1;
            rrDAL.Update();
            var Email = rrDAL.RegisterRequests.Person.Email;
            var Subject = "الاسئلة - موقع سكنا";
            var Message = "اضغط هنا للاجابة على الاسئلة";

            Message = "<a href=\"sokna.org\\RegisterRequests\\QA\\"+rrDAL.RegisterRequests.Id+" \">";

            MailHelpar emailService = new MailHelpar();
            //await emailService.SendEmailAsync(Email, Message, Subject);

            return Json(new { error = false ,data = "تم الارسال بنجاح"}, JsonRequestBehavior.AllowGet);
            //return Json(new { error = true }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult QA(int Id)
        {
            var model = new List<RequestQuestionSenarioViewModel>();
            if (Id != 0)
                model = RequestQuestionSenarioViewModel.GetRequestQuestionSenarioListByRegisterRequests_Id(Id);

            ViewBag.Id = Id;
            RegisterRequestsDAL RR = new RegisterRequestsDAL(Id);

            ViewBag.Status = RR.RegisterRequests.RequestStatus.GetValueOrDefault();

            ViewBag.QA = model;
            ViewBag.ReturnUrl = "RegisterRequest/QA/" + Id;
            return View();
        }

        [HttpPost]
        public ActionResult QA()
        {
            int Id = int.Parse(Request.Params["Id"]);
            var model = new List<RequestQuestionSenarioViewModel>();
            if (Id != 0)
                model = RequestQuestionSenarioViewModel.GetRequestQuestionSenarioListByRegisterRequests_Id(Id);
            foreach(var Q in model)
            {
                var Answers = Request.Params["Answers_"+Q.Id];
                RequestQuestionSenarioDAL RQS = new RequestQuestionSenarioDAL(Q.Id);
                RQS.RequestQuestionSenario.Answers = Answers;
                RQS.Update();
            }
            RegisterRequestsDAL rrDAL = new RegisterRequestsDAL(Id);
            rrDAL.RegisterRequests.RequestStatus = 2;
            rrDAL.Update();
            ViewBag.ReturnUrl = "RegisterRequest/QA/"+ Id;
            return View();
        }
        [HttpPost]
        public ActionResult AcceptApplication(int Id)
        {
            RegisterRequestsDAL rrDAL = new RegisterRequestsDAL(Id);
            rrDAL.RegisterRequests.RequestStatus = 3;
            rrDAL.Update();
            return Json(new { error = false }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult RejecteApplication(int Id)
        {
            RegisterRequestsDAL rrDAL = new RegisterRequestsDAL(Id);
            rrDAL.RegisterRequests.RequestStatus = 4;
            rrDAL.Update();
            return Json(new { error = false }, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #region RR detail
        // GET: RegisterRequest
        public ActionResult Detail(int Id)
        {
            RegisterRequestsDAL rrDAL = new RegisterRequestsDAL(Id);
            RegisterRequestViewModels RR = new RegisterRequestViewModels(rrDAL.RegisterRequests);
            PersonDAL PDAL = new PersonDAL(rrDAL.RegisterRequests.Person_Id.Value);
            PersonViewModel P = new PersonViewModel(PDAL);
            ViewBag.Id = Id;
            ViewBag.Status = RR.RequestStatus.GetValueOrDefault();
            ViewBag.RR = RR;
            ViewBag.P = P;
            return View();
        }
        #endregion

        #region RequestQuestionGVP

        [ValidateInput(false)]
        public ActionResult QuestionBankGVP()
        {
            var model = QuestionBankViewModel.GetQuestionBankList();
            return PartialView("_QuestionBankGVP", model);
        }

        [ValidateInput(false)]
        public ActionResult RequestQuestionGVP(int Id)
        {
            var model = new List<RequestQuestionSenarioViewModel>();
            if (Id != 0)
                model = RequestQuestionSenarioViewModel.GetRequestQuestionSenarioListByRegisterRequests_Id(Id);
            ViewBag.Id = Id;
            RegisterRequestsDAL RR = new RegisterRequestsDAL(Id);
            ViewBag.Status = RR.RegisterRequests.RequestStatus.GetValueOrDefault();

            return PartialView("_RequestQuestionGVP", model);
        }
        
        [HttpPost, ValidateInput(false)]
        public ActionResult RequestQuestionGVPUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] MVCxGridViewBatchUpdateValues<RequestQuestionSenarioViewModel, int> updateValues,int Id)
        {
            ViewBag.Id = Id;
            RegisterRequestsDAL RR = new RegisterRequestsDAL(Id);
            ViewBag.Status = RR.RegisterRequests.RequestStatus.GetValueOrDefault();

            var model = RequestQuestionSenarioViewModel.GetRequestQuestionSenarioListByRegisterRequests_Id(Id);
            // Insert all added values. 
            var newId = model.Count > 0 ? model.Max(i => i.Id) : 0;
            foreach (var item in updateValues.Insert)
            {
                try
                {
                    RequestQuestionSenarioViewModel RQS = new RequestQuestionSenarioViewModel();
                    RQS.Question_id = item.Question_id;
                    RQS.RegisterRequests_Id = Id;
                    RQS.Create();
                    model.Add(RQS);
                }
                catch (Exception e)
                {
                    updateValues.SetErrorText(item, e.Message);
                }
            }
            // Update all edited values. 
            foreach (var item in updateValues.Update)
            {
                try
                {
                    var modelItem = model.FirstOrDefault(it => it.Id == item.Id);
                    if (modelItem != null)
                    {
                        item.Update();
                    }
                }
                catch (Exception e)
                {
                    updateValues.SetErrorText(item, e.Message);
                }
            }
            // Delete all values that were deleted on the client side from the data source. 
            foreach (var ItemID in updateValues.DeleteKeys)
            {
                try
                {
                    var item = model.FirstOrDefault(it => it.Id == Convert.ToInt32(ItemID));
                    if (item != null) item.Delete();
                }
                catch (Exception e)
                {
                    updateValues.SetErrorText(ItemID, e.Message);
                }
            }
            
            return PartialView("_RequestQuestionGVP", model);
        }
        #endregion
    }
}

App.Marriage/App.Marriage/Views/RegisterRequest/Detail.cshtml
@using App.Marriage.Utils;
@{
    ViewBag.Title = "ControlPanel";
}
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var Id = ViewBag.Id;
    var RR = ViewBag.RR;
    var P = ViewBag.P;
}
<script>
    function AcceptApplication_click(s,e) {
        var r = confirm("@Globalization.confrimRegister");
        if (r == true) {
            txt = "You pressed OK!";
            new ss().ajax("/RegisterRequest/AcceptApplication", {
                Id: @ViewBag.Id,
            }, function (e) {
                if (!e.error) {
                    location.reload();
                }
                else {
                    location.reload();
                }
            });
        }
    }
    function RejecteApplication_click(s,e) {
        var r = confirm("@Globalization.RejectRegister");
        if (r == true) {
            new ss().ajax("/RegisterRequest/RejecteApplication", {
                Id: @ViewBag.Id,
            }, function (e) {
                if (!e.error) {
                    location.reload();
                }
                else {
                    location.reload();
                }
            });
        }
    }
</script>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            @Globalization.RegisterRequest
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> @Globalization.controlPanel</a></li>
            <li class="active">@Globalization.RegisterRequest</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <!-- Profile Image -->
                <div class="box box-primary">
                    <div class="box-body box-profile">
                        @*
                        <img class="profile-user-img img-responsive img-circle" src="~/Content/admin/dist/img/avatar5.png" alt="User profile picture">
                        *@
                        <h3 class="profile-username text-center">@P.FullName</h3>
                        <p class="text-muted text-center"></p>
                        <ul class="list-group list-group-unbordered">
                            <li class="list-group-item">
                                <b> @Globalization.father: </b> <strong>@P.Father</strong>
                            </li>
                            <li class="list-group-item">
                                <b>@Globalization.mother : </b> <strong>@P.Mother</strong>
                            </li>
                            <li class="list-group-item">
                                <b>@Globalization.gender : </b> <strong>@((P.Gender == "Male")?"ذكر":"انثى)")</strong>
                            </li>
                        </ul>
                            @if (ViewBag.Status == 3)
                            {
                                <text>
                                <h3 class="bg-success text-center">@Globalization.confrim</h3>
                                </text>
                            }
                            @if (ViewBag.Status == 4)
                            {
                                <text>
                                <h3 class="bg-danger text-center">@Globalization.Reject</h3>
                                </text>
                            }
                            @if (ViewBag.Status != 3 && ViewBag.Status != 4 )
                            {
                                @Html.DevExpress().Button(
                                settings =>
                                {
                                    settings.Name = "AcceptApplication";
                                    settings.Text = Globalization.confrim;
                                    settings.Styles.Native = true;
                                    settings.UseSubmitBehavior = false;
                                    settings.RenderMode = ButtonRenderMode.Link;
                                    settings.ControlStyle.CssClass = "btn btn-primary btn-block";
                                    settings.ClientSideEvents.Click = "AcceptApplication_click";
                                }).GetHtml()
                                    <br />
                                    @Html.DevExpress().Button(
                                settings =>
                                {
                                    settings.Name = "RejecteApplication";
                                    settings.Text = Globalization.Reject;
                                    settings.Styles.Native = true;
                                    settings.UseSubmitBehavior = false;
                                    settings.RenderMode = ButtonRenderMode.Link;
                                    settings.ControlStyle.CssClass = "btn btn-danger btn-block";
                                    settings.ClientSideEvents.Click = "RejecteApplication_click";
                                }).GetHtml()
                            }
                            
                    </div>
                    <!-- /.box-body -->
                </div>
                
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        @*<li><a href="#info" data-toggle="tab">البيانات الشخصية</a></li>*@
                        <li class="active"><a href="#Question" data-toggle="tab">@Globalization.QuestionAndAnswwer</a></li>
                    </ul>
                    <div class="tab-content">                        
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="info">
                            @*@Html.Partial("Profile")*@
                        </div>
                        <div class="active tab-pane" id="Question">
                            <!-- Content -->
                            @Html.Action("RequestQuestionGVP")
                            <!-- /.Content -->
                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<script>
    Array.prototype.remove = function() {
        var what, a = arguments, L = a.length, ax;
        while (L && this.length) {
            what = a[--L];
            while ((ax = this.indexOf(what)) !== -1) {
                this.splice(ax, 1);
            }
        }
        return this;
    };


    var QuestionListHelper = {
        NewRowIndices: [],
        ConfirmPredefinedOrders: function () {
            var handler = function (values) {
                if (values === undefined && values === null) return;
                var length = values.length;
                for (var i = 0; i < length; i++) {
                    var newIndex = QuestionListHelper.AddNewIndex();
                    RequestQuestionGV.AddNewRow();
                    RequestQuestionGV.batchEditApi.EndEdit();
                    var Question_id = values[i];
                    RequestQuestionGV.batchEditApi.SetCellValue(newIndex, "Question_id", Question_id);
                    //RequestQuestionGV.batchEditApi.SetCellValue(newIndex, "RegisterRequests_Id", @ViewBag.Id);
                }
                QuestionBankPopup.Hide();
                QuestionListHelper.ClearPredefinedItemsSelection();
            };
            QuestionBankGV.GetSelectedFieldValues("Id", handler);
        },
        CancelPredefinedOrders: function () {
            QuestionBankPopup.Hide();
            QuestionListHelper.ClearPredefinedItemsSelection();
        },
        ClearPredefinedItemsSelection: function () {
            if (QuestionBankGV.GetSelectedRowCount() > 0)
                QuestionBankGV.UnselectRows();
        },
        AddNewItem: function () {
            RequestQuestionGV.AddNewRow();
            QuestionListHelper.AddNewIndex();
        },
        DeleteItem: function (event) {
            var tr = event.target.parentElement.parentElement.parentElement; // Get the row element
            var id = tr.attributes['id'].value;
            var index = id.split("DataRow")[1];
            RequestQuestionGV.DeleteRow(index);
            QuestionListHelper.NewRowIndices = QuestionListHelper.NewRowIndices.remove(parseInt(index));
        },
        AddNewIndex: function () {
            var newIndex = -1;
            if (QuestionListHelper.NewRowIndices.length > 0)
                newIndex = QuestionListHelper.NewRowIndices[QuestionListHelper.NewRowIndices.length - 1] - 1;
            QuestionListHelper.NewRowIndices.push(newIndex);
            return newIndex;
        }
    };
    function SendQuestions() {
        var r = confirm("@Globalization.msg_SendQuestions");
        if (r == true) {
            new ss().ajax("/RegisterRequest/SendQuestions", {
                Id: @ViewBag.Id,
            }, function (e) {
                if (!e.error) {
                    location.reload();
                }
                else {
                    location.reload();
                }
            });
        }
    }

</script>
@Html.DevExpress().PopupControl(settings =>
{
    settings.Name = "QuestionBankPopup";
    settings.Height = System.Web.UI.WebControls.Unit.Pixel(500);
    settings.Width = System.Web.UI.WebControls.Unit.Pixel(400);
    settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
    settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
    settings.Modal = true;

    settings.ShowHeader = false;
    settings.ShowFooter = true;

    settings.SetContent(() => { Html.RenderPartial("QuestionBank"); });
    settings.SetFooterContentTemplateContent(t =>
    {
        ViewContext.Writer.Write("<div class='container__buttons'>");
        Html.DevExpress().Button(settingsConfirmButton =>
        {
            settingsConfirmButton.Name = "ConfirmButton";
            settingsConfirmButton.Text = Globalization.add;
            settingsConfirmButton.Styles.Native = true;
            settingsConfirmButton.UseSubmitBehavior = false;
            settingsConfirmButton.RenderMode = ButtonRenderMode.Link;
            settingsConfirmButton.ControlStyle.CssClass = "btn btn-primary pull-right btn-margin";
            settingsConfirmButton.ClientSideEvents.Click = "QuestionListHelper.ConfirmPredefinedOrders";
        }).Render();
        Html.DevExpress().Button(settingsCancelButton =>
        {
            settingsCancelButton.Name = "CancelButton";
            settingsCancelButton.Text = Globalization.Cancel;
            settingsCancelButton.Styles.Native = true;
            settingsCancelButton.UseSubmitBehavior = false;
            settingsCancelButton.RenderMode = ButtonRenderMode.Link;
            settingsCancelButton.ControlStyle.CssClass = "btn btn-danger pull-left btn-margin";
            settingsCancelButton.ClientSideEvents.Click = "QuestionListHelper.CancelPredefinedOrders";
        }).Render();
        ViewContext.Writer.Write("</div>");
    });
}).GetHtml()

App.Marriage/App.Marriage/Views/RegisterRequest/Index.cshtml
@{
    ViewBag.Title = "ControlPanel";
}
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script type="text/javascript">
    function CustomButtonClick(s, e, url) {
        var key = s.GetRowKey(e.visibleIndex);
        if (e.buttonID === "detailsButton") {
            var destUrl = url + "/" + key;
            window.location.href = destUrl;
        }
        if (e.buttonID === "acceptButton") {
            popup.Show();
        }
        if (e.buttonID === "rejectButton") {
            popup.Show();
        }
    }

    function OnClickYes(s, e) {
        //GridView.DeleteRow(visibleIndex);
        popup.Hide();
    }
    function OnClickNo(s, e) {
        popup.Hide();
    }

</script>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            طلبات التسجيل
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> لوحة التحكم</a></li>
            <li class="active">طلبات التسجيل</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">جدول الطلبات التسجيل</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">


                        @Html.Action("RegisterRequestGVP")
                        @Html.DevExpress().PopupControl(settings =>
                        {
                            settings.Name = "popup";
                            settings.ShowHeader = true;
                            settings.AllowDragging = true;
                            settings.AllowResize = true;
                            settings.PopupAction = PopupAction.None;
                            settings.PopupElementID = "GridView";
                            //settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
                            settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;

                            settings.HeaderText = "هل تود الاستمرار";

                            settings.SetContent(() =>
                            {

                                @Html.DevExpress().Button(buttonSettings =>
                                {
                                    buttonSettings.Name = "ButtonYes";
                                    buttonSettings.Text = "نعم";
                                    buttonSettings.UseSubmitBehavior = false;
                                    buttonSettings.ClientSideEvents.Click = "OnClickYes";
                                }).Render();
                                @Html.DevExpress().Button(buttonSettings =>
                                {
                                    buttonSettings.Name = "ButtonNo";
                                    buttonSettings.Text = "لا";
                                    buttonSettings.UseSubmitBehavior = false;
                                    buttonSettings.ClientSideEvents.Click = "OnClickNo";
                                }).Render();

                            });
                        }).GetHtml()

                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </div>
    </section>
</div>

App.Marriage/App.Marriage/Views/RegisterRequest/QA.cshtml
@using App.Marriage.DAL
@{
    ViewBag.Title = "QA";
    var status = ViewBag.Status;
}
<div class="row">
    <div class="col-md-8">
        <section id="QA">
            @if (status == 1)
            {
                using (Html.BeginForm("QA", "RegisterRequest", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    
                    <input type="hidden" name="Id" value="@ViewBag.Id" />

                    foreach (var Q in ViewBag.QA)
                    {
                        var quation = new QuestionBankDAL(Q.Question_id);
                        <text>
                        <div class="form-group">
                            <label for="Answers">السؤال : @quation.QuestionBanks.Question</label>
                            <textarea class="form-control" rows="3" name="Answers_@Q.Id" id="Answers" placeholder="الاجابة"></textarea>
                        </div>
                        </text>
                    }
                    <text>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="أرسال الاجابة" class="btn btn-primaray" />
                        </div>
                    </div>
                    </text>
                }
            }
            else
            {
                <div class="flowers"></div>
                <h2>طلبك قيد المعالجة</h2>
                <div class="section-intro">
                    <p>سوف نرسل لك الرد في اقرب وقت</p>
                </div>
            }
        </section>
    </div>
</div>